---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel
  template:
    metadata:
      labels:
        app: otel
    spec:
      containers:
        - name: otel
          image: otel/opentelemetry-collector:latest
          ports:
            - containerPort: 4317
          volumeMounts:
            - name: cfg
              mountPath: /etc/otelcol
      volumes:
        - name: cfg
          configMap:
            name: otel-config

---
apiVersion: v1
kind: Service
metadata:
  name: otel
spec:
  ports:
    - port: 4317
      targetPort: 4317
      name: grpc
  selector:
    app: otel

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-config
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    processors:
      batch:
        timeout: 5s
        send_batch_size: 1024

    exporters:
      otlphttp/logs:
        endpoint: http://loki:3100/otlp

      otlphttp/metrics:
        endpoint: http://mimir:9009/otlp

      otlp/traces:
        endpoint: tempo:4317
        tls:
          insecure: true

    service:
      telemetry:
        logs:
          level: info

      pipelines:
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/logs]

        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/metrics]

        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/traces]
