package pg

import (
	"context"

	"github.com/ehharvey/chat-app/internal/abc"
	"github.com/ehharvey/chat-app/internal/infrastructure/db/pg/generated"
)

type FooRepository struct {
	queries generated.Queries
}

// Generated by check_interface_implementations_test.go to ensure it implements the interface
// TODO: Methods meant for Bar shouldn't have (r FooRepository) receiver, should be (r BarRepository) instead
// CheckExistsBarByName implements abc.Repository.
func (r FooRepository) CheckExistsBarByName(ctx context.Context, input abc.CheckExistsBarByNameParams) (abc.CheckExistsBarByNameModel, error) {
	panic("unimplemented")
}

// InsertOneBar implements abc.Repository.
func (r FooRepository) InsertOneBar(ctx context.Context, input abc.InsertOneBarParams) (abc.BarModel, error) {
	panic("unimplemented")
}

func NewFooRepository(queries generated.Queries) FooRepository {
	return FooRepository{
		queries: queries,
	}
}

func (r FooRepository) InsertOneFoo(
	ctx context.Context,
	input abc.InsertOneFooParams,
) (abc.FooModel, error) {
	result, err := r.queries.InsertOneFoo(ctx, input.Name)

	// TODO: Consider logging
	// TODO: Consider altering err instead of just bubbling up

	return abc.FooModel{
		ID:   result.ID.String(),
		Name: result.Name,
	}, err
}

func (r FooRepository) CheckExistsFooByName(
	ctx context.Context,
	input abc.CheckExistsFooByNameParams,
) (abc.CheckExistsFooByNameModel, error) {
	result, err := r.queries.CheckExistsFooByName(ctx, input.Name)

	return abc.CheckExistsFooByNameModel{
		Exists: result,
	}, err
}
